# https://infinum.co/the-capsized-eight/hiding-secrets-in-vault
default: &default
  secret_key_base: <%= Figaro.env.secret_key_base! %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default